---
- hosts: bluejayserver
  tasks: 
    
    - name: Clean Local App Clone
      become: yes
      file:
        path: /home/ubuntu/vanhackathon-nestready
        state: absent
    
    - name: Clone App Repository
      become: no
      command: git clone https://github.com/lucasgeds/vanhackathon-nestready 
    
    - name: Install Packages
      become: yes  
      apt: 
        name: ['ruby2.5', 'ruby2.5-dev', 'build-essential', 'patch', 'zlib1g-dev', 'liblzma-dev', 'postgresql', 'postgresql-server-dev-all', 'nodejs']
        state: present

    - name: Install PostgreSQL Config
      become: yes
      template: src=files/pg_hba.conf dest=/etc/postgresql/10/main/pg_hba.conf

    - name: Restart PostgreSQL
      become: yes
      service:
        name: postgresql
        state: restarted

    - name: Install Gem Bundler
      become: yes
      command: gem install bundler
      
    - name: Install Gem Nokogiri
      become: yes
      command: gem install nokogiri -v '1.10.1' --source 'https://rubygems.org/'

    - name: Install Project Libs
      become: yes
      command: bundle install 
      args:
        chdir: /home/ubuntu/vanhackathon-nestready/bluejay_api

    - name: Run App DB Setup
      become: yes
      command: bundle exec rails db:setup
      args:
        chdir: /home/ubuntu/vanhackathon-nestready/bluejay_api

    - name: Run App DB Seed
      become: yes
      command: bundle exec rails db:seed
      args:
        chdir: /home/ubuntu/vanhackathon-nestready/bluejay_api

    - name: Run App Server
      become: yes
      shell: cd /home/ubuntu/vanhackathon-nestready/bluejay_api; nohup bundle exec rails server --binding 0.0.0.0 --port 3000 </dev/null >/dev/null 2>&1 &


